### ISSUE TITLE
Question: can be used for satellite location estimation?

### ISSUE THREAD

**Issue by Tylersuard** [pearsonkyle/Nbody-TTV-Retrieval#1]
Hello!  This is a really cool project.  I like that it uses AI to solve the n-body problem.  Would I be able to get this to work on the problem of tracking satellite orbits?  It seems to me I could just have the sun, moon, earth, and satellite as objects in the simulation.

**Comment by pearsonkyle** [comment]
You can easily use this library to set up an N-body simulation with those objects. The N-body code is based on [REBOUND](https://rebound.readthedocs.io/en/latest/) so it's very precise, as long as you have a small enough time step. 

It might be possible to apply machine learning to your problem but it depends on what you're trying to figure out. If you want a precise location, your best bet might be to just integrate an N-body simulation. If you need to optimize some parameters, perhaps that can be expedited with machine learning.

**Comment by Tylersuard** [comment]
Thank you :)
